package it.polimi.ingsw.communication.message;

import it.polimi.ingsw.communication.MessageVisitor;

public interface MessageVisitable{
    String LOGIN_MESSAGE_PREFIX = "#LOGIN#";
    String GENERIC_MESSAGE_PREFIX = "#GENERIC#";
    String LAYOUTUPDATE_MESSAGE_PREFIX = "#LAYOUTUPDATE#";
    String KILLSHOTUPDATE_MESSAGE_PREFIX = "#KILLSHOTUPDATE#";
    String CURRENTPLAYERUPDATE_MESSAGE_PREFIX = "#CURRENTPLAYERUPDATE#";
    String STARTMATCHUPDATE_MESSAGE_PREFIX = "#STARTMATCHUPDATE#";
    String PLAYERUPDATEMESSAGE_MESSAGE_PREFIX = "#PLAYERUPDATEMESSAGE#";
    String PAYMENTUPDATE_MESSAGE_PREFIX = "#PAYMENTUPDATE#";
    String WEAPONSUPDATE_MESSAGE_PREFIX = "#WEAPONSUPDATE#";
    String POWERUPUPDATE_MESSAGE_PREFIX = "#POWERUPUPDATE#";
    String SELECTABLESUPDATE_MESSAGE_PREFIX = "#SELECTABLESUPDATE#";
    String DAMAGEUPDATE_MESSAGE_PREFIX = "#DAMAGEUPDATE#";
    String CONNECTIONUPDATE_MESSAGE_PREFIX = "#CONNECTIONUPDATE#";
    String GAMEOVER_MESSAGE_PREFIX = "#GAMEOVER#";

    void accept(MessageVisitor messageVisitor);
}
